### ISSUE TITLE
Change opening behavior on mobile 

### ISSUE THREAD

**Issue by Moncef12** [smartsupp/smartsupp.github.io#11]
Hello, 

Is it possible to open the chat on mobile the same way it's done on large devices? We don't want to have a new window opened.

I took a look to at the API but it seems there is no option to force this. 

Thanks.

**Comment by tohoracek** [comment]
Hi,

currently, it is not possible to open chat in the same window on mobile.

However, we are going to launch the update of the widget in a few weeks.

Tomas
